# Generated by Selenium IDE（千代田図書館で詳細検索）
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("https://www.library.chiyoda.tokyo.jp/")
    self.driver.set_window_size(1440, 875)
    self.driver.find_element(By.LINK_TEXT, "詳細検索").click()
    self.driver.find_element(By.ID, "word1").click()
    self.driver.find_element(By.ID, "word1").send_keys("Python")
    self.driver.find_element(By.ID, "txt_stpubdate").click()
    self.driver.find_element(By.ID, "txt_stpubdate").send_keys("2017")
    self.driver.find_element(By.ID, "txt_edpubdate").click()
    self.driver.find_element(By.ID, "txt_edpubdate").send_keys("2019")
    self.driver.find_element(By.NAME, "submit_btn_searchDetailSelAr").click()
  
